apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app4ingress
  name: app4ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4ingress
  template:
    metadata:
      labels:
        app: app4ingress
    spec:
      containers:
      - image: robertsilvatech/app4ingress
        name: app4ingress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app4ingress
  name: app4ingress
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app4ingress